version: "3.8"

services:
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    # depends_on:
    #   - mariadb
  nginx:
    build: requirements/wordpress/.
    container_name: nginx
    ports:
      - "80:80"
    # depends_on:
    #   - wordpress

  mariadb:
    build: requirements/wordpress/.
    container_name: mariadb
    env_file: .env
