
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - 42network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MADANI_USER}", "-p${MADANI_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - 42network
    restart: always
  
  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
      - mariadb
    env_file: .env
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  
  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - 42network
    restart: always

  static:
    build: requirements/bonus/static
    container_name: static
    ports:
      - "8081:80"
    networks:
      - 42network
    restart: always

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - 42network


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eamchart/data/wordpress
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eamchart/data/mariadb
  
  portainer_data:
    name: portainer_data

networks:
  42network:
    driver: bridge