
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    secrets:
      - db_user
      - db_password
      - db_root_password
      - db_database
    networks:
      - 42network
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    secrets:
      - db_user
      - db_password
      - db_database
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_email
      - wp_user_password
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - 42network
    restart: always
  
  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
      - mariadb
    env_file: .env
    networks:
      - 42network
    volumes:
      - wordpress_data:/var/www/html
    restart: always
  
  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - 42network
    restart: always

  static:
    build: requirements/bonus/static
    container_name: static
    ports:
      - "8081:80"
    networks:
      - 42network
    restart: always

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - 42network


volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eamchart/data/wordpress
  
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/eamchart/data/mariadb
  
  portainer_data:
    name: portainer_data

networks:
  42network:
    driver: bridge

secrets:
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_database:
    file: ../secrets/db_database.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_user_email:
    file: ../secrets/wp_user_email.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt